// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-sJjXwv9wkTPfaAs4tWDklP1ieR0ciMY',
    appId: '1:888220178741:web:4ea38a47d5c540352e547c',
    messagingSenderId: '888220178741',
    projectId: 'task-flow-2b43f',
    authDomain: 'task-flow-2b43f.firebaseapp.com',
    storageBucket: 'task-flow-2b43f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjwgTiEm6i4J1pauksBOGlQPZ47TR-Wq0',
    appId: '1:888220178741:android:2fedeb422a68fec22e547c',
    messagingSenderId: '888220178741',
    projectId: 'task-flow-2b43f',
    storageBucket: 'task-flow-2b43f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY76avKEEA-fUn6X34a4h679MuaaokiYU',
    appId: '1:888220178741:ios:8ff71696a319b9702e547c',
    messagingSenderId: '888220178741',
    projectId: 'task-flow-2b43f',
    storageBucket: 'task-flow-2b43f.firebasestorage.app',
    iosBundleId: 'com.example.taskFlow',
  );
}
